[package]
name = "dolores"
version = "0.1.0"
authors = ["Łukasz Niemier <lukasz@niemier.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
split-debuginfo = "unpacked"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
bincode = "1.3"
nix = "0.20.0"
rand = "0.8"
rcgen = "0.8"
rustls = "0.19"
serde = { version = "1.0", features = ["derive"] }
slog = { version = "2.7", features = ["max_level_trace"] }
slog-term = "2"
structopt = "0.3.21"
tokio = { version = "1", features = ["full"] }
tokio-rustls = "0.22"
strum = { version = "0.20", features = ["derive"] }
